from time import sleep
nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...')
sleep(1)
print('Seu nome em maiúsculas: {}'.format(nome).upper())
sleep(1)
print('Seu nome em minúsculas: {}'.format(nome).lower())
sleep(1)
print('Seu nome tem ao todo {} letras.'.format(len(nome)-nome.count(' ')))
sleep(1)
print('Seu primeiro nome tem {} letras.'.format(nome.find(' ')))
separa = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras.'.format(separa[0], len(separa[0])))
